spring.application.name=election-backend
spring.datasource.url=jdbc:mysql://localhost:3306/election-portal-db
spring.datasource.username=root
spring.datasource.password=2400031598

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true